using System;
using ClassLibraryForArray;

namespace ConsoleAppTest
{
    class Program
    {
        static void Main(string[] args)
        {
            IntArray.Notify += DisplayMessage;

            IntArray arr = new IntArray(3, 4, 4, 4, 5);
            IntArray randomArr = IntArray.RandomIntArray(10, 2, 5);
            IntArray arrFromFile = IntArray.ArrayFromTextFile("D:\\input.txt");

            Console.WriteLine("\n\nOUTPUT CREATED ARRAYS\n\n");
            Console.WriteLine("First arr:");
            PrintArr(arr);
            Console.WriteLine("\nArray generated by random numbers:");
            PrintArr(randomArr);
            Console.WriteLine("\nArray read from file:");
            PrintArr(arrFromFile);

            Console.WriteLine("\n\n\nCHECK METHODS ON FIRST ARRAY\n\n");
            IntArray.ArrayToTextFile(arr, "D:\\output.txt");
            IntArray.SumArray(arr);
            arr++;
            arr--;

            Console.ReadKey();
        }
        private static void DisplayMessage(string message) => Console.WriteLine(message);
        private static void PrintArr (IntArray arr)
        {
            for (int i = 0; i < arr.Length; i++)
                Console.Write(arr[i] + " ");
        }
    }
}
